### ISSUE TITLE
遇到了一个问题能帮我看下吗？？Vue-router跳转之后layui的js就失去效果了，怎么解决

### ISSUE THREAD

**Issue by Suckson** [kouchao/vue-layui#5]

**Comment by kouchao** [comment]
麻烦提供以下代码截图

**Comment by Suckson** [comment]
![image](https://user-images.githubusercontent.com/38757109/50396351-8a6de680-07a4-11e9-8c64-7dedfb4a20d2.png)
引入我是直接在index引入的静态js  css  然后页面在路由跳转的时候就不执行js   组件的js是可以执行的  刷新页面就可以了

**Comment by kouchao** [comment]
建议您参考官方文档，或向[layui官方](https://github.com/sentsin/layui)讨论，本仓库是基于layui样式和vue组件重新编写逻辑。已经抛除了layui.js以及jquery。

**Comment by Suckson** [comment]
我看了你写的代码？？666   echars 能不能在集成一下，比较期待

**Comment by kouchao** [comment]
@Suckson echars 或者其他的图表组件应该已经有人封装了，可以搜一下看看
