### ISSUE TITLE
兄弟 这个怎么使用啊 跟layui一样吗

### ISSUE THREAD

**Issue by 1014470807** [kouchao/vue-layui#6]
兄弟 这个怎么使用啊 跟layui一样吗

**Comment by kouchao** [comment]
文档正在建设中，请参考[demo源码](https://github.com/kouchao/vue-layui/tree/dev/src/views)

**Comment by 1014470807** [comment]
这个是你们的民间组织重新弄的吗 想加入你们一起弄 有QQ或者微信群吗

**Comment by bulusite** [comment]
@1014470807  这里有个钉钉二维码[http://vue-layui.jskou.com/#/about](url)
